namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum CardState : byte
{
    //TODO
    CARDHOUSE_CARDSTATE_INVALID = 0,
    CARDHOUSE_CARDSTATE_FREE = 1,
    CARDHOUSE_CARDSTATE_INGAME = 2,
    CARDHOUSE_CARDSTATE_INCARDSELL = 3,
    CARDHOUSE_CARDSTATE_ONLINESWAP = 4,
    CARDHOUSE_CARDSTATE_IMPROVEDSALE = 5,
    CARDHOUSE_CARDSTATE_PARTOFOFFER = 6,
    CARDHOUSE_CARDSTATE_ACTIVE_BADGE = 100,
    CARDHOUSE_CARDSTATE_ACTIVE_HOME_KIT = 101,
    CARDHOUSE_CARDSTATE_ACTIVE_AWAY_KIT = 102,
    CARDHOUSE_CARDSTATE_ACTIVE_STADIUM = 104,
    CADHOUSE_CARDSTATE_MAXIMUM_STATE = 254,
    CARDHOUSE_CARDSTATE_SEARCH_ACTIVE = 255
}