namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum DeckType : uint
{
    //TODO ID'S Are not all confirmed
    CARDHOUSE_DECK_INVALID = 0,
    CARDHOUSE_DECK_SQUAD = 1,
    CARDHOUSE_DECK_TRAINING = 2,
    CARDHOUSE_DECK_GAMEPLAY = 3,
    CARDHOUSE_DECK_ACTIVE = 4,
    CARDHOUSE_DECK_ESCROW = 5,
    CARDHOUSE_DECK_UNASSIGNED = 6,
    CARDHOUSE_DECK_STICKERBOOK = 7,
    CARDHOUSE_DECK_INBOX = 8,
    CARDHOUSE_DECK_GENERAL = 9,
}