namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum OfferState : int
{
    CARDHOUSE_OFFERSTATE_INVALID = 0,
    CARDHOUSE_OFFERSTATE_ACTIVE = 1,
    CARDHOUSE_OFFERSTATE_ACCEPTED = 2,
    CARDHOUSE_OFFERSTATE_REJECTED = 3,
    CARDHOUSE_OFFERSTATE_CANCELED = 4,
    CARDHOUSE_OFFERSTATE_OUTBID = 5,
    CARDHOUSE_OFFERSTATE_TRADECLOSED = 6,
    CARDHOUSE_OFFERSTATE_WINNINGBID = 7,
}