namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum RequestContext : byte
{
    //TODO Not all confirmed
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_INVALID = 0,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_TOP = 1,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_YEAR = 2,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_COUNTRY = 3,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_LEAGUE = 4,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_NEW_CARDS_SCREEN = 5,
    CARDHOUSE_STICKERBOOK_STATS_REQUEST_CONTEXT_MAX = 6,
}