namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum StoreSaleType : byte
{
    /// TODO Id's not confirmed
    CARDHOUSE_STORESALETYPE_NONE = 0,
    CARDHOUSE_STORESALETYPE_QUANTITY = 1,
    CARDHOUSE_STORESALETYPE_TIME = 2,
    CARDHOUSE_STORESALETYPE_PRICE = 3,
    CARDHOUSE_STORESALETYPE_JUMBO = 4,
    CARDHOUSE_STORESALETYPE_TIME_AND_QUANTITY = 5,
    CARDHOUSE_STORESALETYPE_MAX = 6,
}