namespace Zamboni14Legacy.Components.NHL14Legacy.Structs.Hut;

public enum TournamentRule : int
{
    SEASONALPLAY_TOURNAMENTRULE_UNLIMITED = 1,
    SEASONALPLAY_TOURNAMENTRULE_RETRY_ON_LOSS = 2,
    SEASONALPLAY_TOURNAMENTRULE_ONE_ATTEMPT = 3
}